# Copyright 2017 Joaquín M López Muñoz.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# See http://www.boost.org/libs/poly_collection for library home page.


sudo: false

language: cpp

os: linux
    
branches:
  only:
    - master

matrix:
  exclude: # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
    - language: cpp
    - os: linux
    - branches:
       only:
         - master
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: B2_OPTIONS=toolset=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: B2_OPTIONS='toolset=clang'
#            - g++-5
#      env: B2_OPTIONS='toolset=clang cxxflags=-isystem/usr/include/c++/5'

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init
  - rcp -r $TRAVIS_BUILD_DIR libs/poly_collection/
  - ./bootstrap.sh
  - ./b2 headers

script:
  - "echo 'using clang : 3.7 : clang++-3.7 ;' > $HOME/user-config.jam"
  - ./b2 libs/poly_collection/test $B2_OPTIONS

notifications:
  email:
    on_success: always