# Copyright 2017 Joaquín M López Muñoz.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# See http://www.boost.org/libs/poly_collection for library home page.

language: cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - master

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init
  - rcp -r $TRAVIS_BUILD_DIR libs/poly_collection/
  - ./bootstrap.sh
  - ./b2 headers

script:
  - TOOLSET=gcc,clang
  - if [ $TRAVIS_OS_NAME == osx ]; then TOOLSET=clang; fi
  - ./b2 libs/poly_collection/test toolset=$TOOLSET

notifications:
  email:
    on_success: always